# GitBook Configuration for LookCoin Documentation

# Root directory for documentation
root: ./

# Structure configuration
structure:
  readme: README.md
  summary: ./docs/SUMMARY.md

# Site metadata
title: "LookCoin Documentation"
description: "Complete documentation for LookCoin omnichain fungible token"
author: "LookCard Development Team"
language: "en"

# Plugin configuration
plugins:
  - search
  - mermaid-gb3
  - code-block-enhanced
