[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache_forge"

# Solc configuration
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test configuration
verbosity = 2
gas_reports = ["*"]
gas_snapshots = true

# Fork configuration
eth_rpc_url = "https://rpc.ankr.com/eth"
bsc_rpc_url = "https://bsc-dataseed1.binance.org/"
polygon_rpc_url = "https://rpc.ankr.com/polygon"

# Remappings
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "@layerzerolabs/oft-evm/=node_modules/@layerzerolabs/oft-evm/",
    "@layerzerolabs/lz-evm-protocol-v2/=node_modules/@layerzerolabs/lz-evm-protocol-v2/",
    "@layerzerolabs/lz-evm-messagelib-v2/=node_modules/@layerzerolabs/lz-evm-messagelib-v2/",
    "@hyperlane-xyz/core/=node_modules/@hyperlane-xyz/core/",
    "forge-std/=node_modules/forge-std/src/"
]

# Performance optimization for load tests
ffi = true
fs_permissions = [{ access = "read-write", path = "./reports/" }]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20, fail_on_revert = true }

[profile.intense]
fuzz = { runs = 50000 }
invariant = { runs = 5000, depth = 50 }

# Load testing profile with extended limits
[profile.load_test]
gas_limit = 18446744073709551615
gas_price = 0
block_gas_limit = 18446744073709551615
memory_limit = 134217728  # 128MB
fuzz = { runs = 100000 }
invariant = { runs = 10000, depth = 100 }
verbosity = 3

[fuzz]
runs = 1000
max_test_rejects = 65536
seed = "0x42"

[invariant]
runs = 1000
depth = 20
fail_on_revert = false
call_override = false
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Gas reporting configuration
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"